name: test

on:
    push:

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      generate_slack_payload: ${{ steps.generate_slack_payload.outputs.SLACK_PAYLOAD }}
    steps:
      - name: Generate slack JSON payload and save it to an output variabe
        id: generate_slack_payload
        run: |
          TOKEN=$(echo '[{"name":"aaronddm-demo-package-a","version":"0.0.2-prealpha.1"}]' | jq '{ "text": "New releases", "blocks": [.[] | {"type": "section", "text": { "type": "mrkdwn", "text": "Released version \\(.version) for \\(.name)"}}]}')
          echo "SLACK_PAYLOAD=$TOKEN" >> $GITHUB_OUTPUT

      - name: Print the output
        run: |
          echo '${{ steps.generate_slack_payload.outputs.SLACK_PAYLOAD }}'
